[package]
name = "parse_ncbi_gtf"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
noodles-gtf = "0.52.0"
glob = "0.3.3"
noodles-fasta = "0.61.0"
noodles-gff = "0.57.0"
bstr = "1.12.1"
noodles-core = "0.20.0"
serde = {version = "1.0.228", features = ["derive"]}
reqwest = "0.13.4"
rand = "0.10.2"
num = "0.4.3"
histogram = "1.5.0"
